/*
 * Created on 26 thg 8 2016 ( Time 11:30:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.rest.controller;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpSession;

import org.json.simple.JSONObject;
import org.json.simple.parser.*;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.trams.bean.UserItem;
import org.trams.bean.Setting;
import org.trams.bean.jpa.SettingEntity;
import org.trams.business.service.SettingService;
import org.trams.rest.common.AbstractRestController;
import org.trams.rest.common.AuthorizationToken;
import org.trams.web.common.utils.DataUtils;
/**
 * Spring MVC controller for 'Setting' management.
 */
@RequestMapping("/setting")
@Controller
public class SettingRestController extends AbstractRestController{

	@Resource
	private SettingService settingService;
	
		
	@RequestMapping( value="/all",
			method = {RequestMethod.POST, RequestMethod.GET},
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public HashMap<String, Object> findAll(
	@RequestHeader(value="token") String token
	) {
		//UserItem user =AuthorizationToken.convertToObject(token);
		try {
			List<Setting> list = settingService.findAll();
			return SUCCESS(list);
		} catch (Exception e) {
			return FAIL("HAVE ERROR: "+e);
		}
	} 
	
	@RequestMapping( value="/paging",
			method = {RequestMethod.POST, RequestMethod.GET},
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public HashMap<String, Object> findAllPaging(
	@RequestHeader(value="token",required=false) String token,
	@RequestBody String json
	) throws ParseException {
		//UserItem user =AuthorizationToken.convertToObject(token);
		HashMap<String, Object> ret =new HashMap<String, Object>();
		try {
			JSONParser parser = new JSONParser();
			JSONObject jsonObj = (JSONObject) parser.parse(json);
			Integer page = DataUtils.parseInt(jsonObj.get("page"));
			Page<SettingEntity> list = settingService.findAll(page);
			if(list.getContent()!=null){
				ret.put("list", list.getContent());
				ret.put("page", page);
				ret.put("totalPage", list.getTotalPages());
				return SUCCESS(ret);
			}else{
				return SUCCESS();
			}
		} catch (Exception e) {
			return FAIL("HAVE ERROR: "+e);
		}
		
	} 
	@RequestMapping( value="/item",
			method = {RequestMethod.POST, RequestMethod.GET},
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public HashMap<String, Object> findOne(
	@RequestHeader(value="token") String token
		) {
		UserItem user =AuthorizationToken.convertToObject(token);
		try {
			Setting item= settingService.findById(user.getId());
			if(item!=null){
				
				return SUCCESS(item);
			}else{
				item = new Setting();
				item.setId(user.getId());
				item.setCommentNotification(1);
				item.setCouponNotification(1);
				item.setFinishPayCourseNotification(1);
				item.setFinishRegisterCourseNotification(1);
				item.setNoticeNotification(1);
				item.setOpenCourseNotification(1);
				item.setPostCommentCourseNotification(1);
				item.setPostQuestionCourseNotification(1);
				item.setUploadContentNotification(1);
				item.setId(user.getId());
				item.setCreateDate(DataUtils.getNowDate());
				item.setUpdateDate(DataUtils.getNowDate());
				Setting create= settingService.create(item);
				return SUCCESS(create);
			}
		} catch (Exception e) {
			return FAIL("HAVE ERROR: "+e);
		}
	}
	
	@RequestMapping( value="/create",
			method = {RequestMethod.POST, RequestMethod.GET},
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public HashMap<String, Object> create(
	@RequestHeader(value="token",required=false) String token,
	@RequestBody Setting item
	) {
	try{
			UserItem user =AuthorizationToken.convertToObject(token);
			SettingEntity s = settingService.findByUserId(user.getId());
			if(s == null){
				item.setId(user.getId());
				item.setCreateDate(DataUtils.getNowDate());
				item.setUpdateDate(DataUtils.getNowDate());
				Setting create= settingService.create(item);
				return SUCCESS(create);
			}else{
				return FAIL("User created setting ");
			}
			
		}catch(Exception e){
			System.out.println(e);
			return FAIL("HAVE ERROR: "+e);
		}
	}

	@RequestMapping( value="/edit",
			method = {RequestMethod.POST, RequestMethod.GET},
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public HashMap<String, Object> edit(
	@RequestHeader(value="token",required=false) String token,
	@RequestBody Setting item
	) {
	try{
			UserItem user =AuthorizationToken.convertToObject(token);
			Setting s = settingService.findById(user.getId());
			item.setId(user.getId());
			item.setUpdateDate(DataUtils.getNowDate());
			item.setCreateDate(s.getCreateDate());
			Setting edit=settingService.update(item);
			return SUCCESS(edit);
		}catch(Exception e){
			System.out.println(e);
			return FAIL("HAVE ERROR: "+e);
		}
	}

	@RequestMapping( value="/delete/{id}",
			method = {RequestMethod.POST, RequestMethod.GET},
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public HashMap<String, Object> delete(
	@RequestHeader(value="token",required=false) String token,
	@PathVariable("id") Integer id) {
		try{
				settingService.delete(id);
				return SUCCESS();
		}catch(Exception e){
				System.out.println(e);
				return FAIL("HAVE ERROR: "+e);
		}
	}
	
}



