/*
 * Created on 13 thg 9 2016 ( Time 14:25:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.web.controller;

import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpSession;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ModelAttribute;


//--- Common classes
import org.trams.web.common.AbstractController;
import org.trams.web.common.Pager;
import org.trams.web.common.utils.DataUtils;
import org.trams.bean.jpa.ContentRelatedEntity;

//--- Entities
import org.trams.bean.ContentRelated;

//--- Services 
import org.trams.business.service.ContentRelatedService;
import org.trams.business.service.ContentService;
import org.trams.business.service.ProgramService;

/**
 * Spring MVC controller for 'ContentRelated' management.
 */
@Controller
@RequestMapping("/contentRelated")
public class ContentRelatedController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "contentRelated";

	private static final Integer PAGE_SIZE   = 10;

	private static String nav = "contentRelated";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_CREATE   = "contentRelated/create";
	private static final String JSP_LIST   = "contentRelated/list";
	private static final String JSP_EDIT   = "contentRelated/edit";
	private static final String JSP_DETAIL   = "contentRelated/detail";
	private static final String MAIN_LIST_NAME   = "list";
	//--- Main entity service
	@Resource
    private ContentRelatedService contentRelatedService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private ContentService contentService; // Injected by Spring
	@Resource
    private ProgramService programService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public ContentRelatedController() {
		super(ContentRelatedController.class, MAIN_ENTITY_NAME );
		log("ContentRelatedController created.");
	}

	@RequestMapping("/list")
	public String list(
			@RequestParam(value="page",defaultValue="1") Integer page,
			@RequestParam(value="type",defaultValue="id") String type,
			@RequestParam(value="key",defaultValue="") String key,
			@RequestParam(value="delete",defaultValue="0") Integer delete,
			HttpSession session,
			Model model) {
		if(key==null){
			key="";
		}
		if(type==null){
			type="";
		}
		if(delete>0){
			try {
				contentRelatedService.delete(delete);
			} catch (Exception e) {
				// TODO: handle exception
			}
		}
		Page<ContentRelatedEntity> listPage = null;
		if(type == ""){
			listPage = contentRelatedService.listPaging(page, PAGE_SIZE);
		}
		model.addAttribute(MAIN_LIST_NAME, listPage);	
		model.addAttribute("key", key);
		model.addAttribute("type", type);
		model.addAttribute("activePage", nav);
		model.addAttribute("pagination_navigator", "/contentRelated/list");
		new Pager<ContentRelatedEntity>(listPage).setSetting(model, "type="+type+"&amp;key="+key+"&amp;");		
		return JSP_LIST;
	}

	
	@RequestMapping("/detail/{id}")
	public String detail(
	Model model, 
	HttpSession session,
	@PathVariable("id") Integer id) {
		ContentRelated contentRelated = contentRelatedService.findById(id);
		model.addAttribute("contentRelated", contentRelated);
		model.addAttribute("activePage", nav);
		return JSP_DETAIL;
	}
	@RequestMapping(value = "/create", method = RequestMethod.GET ) 
	public String create(
			HttpSession session,
			Model model) {
		log("Action 'create'");
		model.addAttribute("activePage", nav);
		return JSP_CREATE;
	}

	@RequestMapping(value = "/create", method = RequestMethod.POST ) 
	public String create(
			HttpSession session,
			@ModelAttribute ContentRelated contentRelated,
			Model model) {
		log("Action 'create'");
		try {
			contentRelated.setCreateDate( DataUtils.getNowDate() );
			contentRelated.setUpdateDate( DataUtils.getNowDate() );
			contentRelatedService.create(contentRelated);
			return "redirect:/"+JSP_LIST;
		} catch(Exception e) {
			System.out.println(e);
			return JSP_CREATE;
		}
	}

	@RequestMapping(value = "/edit/{id}", method = RequestMethod.GET)
	public String update(
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
		ContentRelated contentRelated = contentRelatedService.findById(id);
		try {
			model.addAttribute("item", contentRelated);
			model.addAttribute("activePage", nav);
			return JSP_EDIT;
		} catch(Exception e) {
			return JSP_LIST;
		}
	}
	
	@RequestMapping(value = "/edit/{id}", method = RequestMethod.POST)
	public String update(
	@RequestParam(value="edit",defaultValue="0") Integer edit,
	@ModelAttribute ContentRelated item,
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
		ContentRelated contentRelated = contentRelatedService.findById(id);
		try {
			contentRelated.setUpdateDate( DataUtils.getNowDate() );
			contentRelated = contentRelatedService.update(contentRelated);
			model.addAttribute("item", contentRelated);
		} catch(Exception e) {
			System.out.println(e);
		}
		return "redirect:/"+JSP_EDIT+"/"+id;
	}
	
	

	@RequestMapping(value = "/delete/{id}")
	public String delete(
	Model model, 
	HttpSession session,
	@PathVariable("id") Integer id ) {
	contentRelatedService.delete(id);
	return "redirect:/"+JSP_LIST;
	}

}
