/*
 * Created on 19 thg 9 2016 ( Time 19:18:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.web.controller;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.annotation.Resource;
import javax.mail.Multipart;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import org.springframework.web.bind.annotation.ModelAttribute;


//--- Common classes
import org.trams.web.common.AbstractController;
import org.trams.web.common.Pager;
import org.trams.web.common.utils.DataUtils;
import org.trams.web.common.utils.FileUtils;
import org.trams.web.common.Login;
import org.trams.bean.jpa.EventEntity;

//--- Entities
import org.trams.bean.Event;

//--- Services 
import org.trams.business.service.EventService;

/**
 * Spring MVC controller for 'Event' management.
 */
@Controller
@RequestMapping("/event")
public class EventController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "event";

	private static final Integer PAGE_SIZE   = 10;

	private static String nav = "event";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_CREATE   = "event/create";
	private static final String JSP_LIST   = "event/list";
	private static final String JSP_EDIT   = "event/edit";
	private static final String JSP_DETAIL   = "event/detail";
	private static final String JSP_LOGIN   = "redirect:/login";
	private static final String MAIN_LIST_NAME   = "list";
	//--- Main entity service
	@Resource
    private EventService eventService; // Injected by Spring
	@Resource
    private ServletContext servletContext;
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public EventController() {
		super(EventController.class, MAIN_ENTITY_NAME );
		log("EventController created.");
	}

	@RequestMapping("/list")
	public String list(
			@RequestParam(value="page",defaultValue="1") Integer page,
			@RequestParam(value="type",defaultValue="") String type,
			@RequestParam(value="key",defaultValue="") String key,
			@RequestParam(value="delete",defaultValue="0") Integer delete,
			HttpSession session,
			Model model) {
		if(key==null){
			key="";
		}
		if(type==null){
			type="";
		}
		if(delete>0){
			try {
				eventService.delete(delete);
			} catch (Exception e) {
				// TODO: handle exception
			}
		}
		Page<EventEntity> listPage = null;
		if(type == ""){
			listPage = eventService.listPaging(page, PAGE_SIZE);
		}
		else if(type.equals("title")){
			listPage = eventService.findByTitle("%"+key+"%", page, PAGE_SIZE);
		}
		model.addAttribute(MAIN_LIST_NAME, listPage);	
		model.addAttribute("key", key);
		model.addAttribute("type", type);
		model.addAttribute("activePage", nav);
		model.addAttribute("pagination_navigator", "/event/list");
		new Pager<EventEntity>(listPage).setSetting(model, "type="+type+"&amp;key="+key+"&amp;");		
		return JSP_LIST;
	}

	
	@RequestMapping("/detail/{id}")
	public String detail(
	Model model, 
	HttpSession session,
	@PathVariable("id") Integer id) {
		Event event = eventService.findById(id);
		model.addAttribute("event", event);
		model.addAttribute("activePage", nav);
		return JSP_DETAIL;
	}
	@RequestMapping(value = "/create", method = RequestMethod.GET ) 
	public String create(
			HttpSession session,
			Model model) {
		log("Action 'create'");
		model.addAttribute("activePage", nav);
		return JSP_CREATE;
	}

	@RequestMapping(value = "/create", method = RequestMethod.POST ) 
	public String create(
			HttpSession session,
			@ModelAttribute Event event,
			@RequestParam(value="file") MultipartFile file,
			Model model) {
		log("Action 'create'");
		try {
			if(file.getSize() > 0){
				String path = FileUtils.saveFileOrigin(file,"upload", servletContext);
				event.setImageUrl(path);
				event.setImageName(file.getOriginalFilename());
			}
			event.setViewCount(0);
			event.setCreateDate( DataUtils.getNowDate() );
			event.setUpdateDate( DataUtils.getNowDate() );
			eventService.create(event);
			return "redirect:/"+JSP_LIST;
		} catch(Exception e) {
			System.out.println(e);
			return JSP_CREATE;
		}
	}

	@RequestMapping(value = "/edit/{id}", method = RequestMethod.GET)
	public String update(
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
		Event event = eventService.findById(id);
		try {
			model.addAttribute("item", event);
			model.addAttribute("activePage", nav);
			return JSP_EDIT;
		} catch(Exception e) {
			return JSP_LIST;
		}
	}
	
	@RequestMapping(value = "/edit/{id}", method = RequestMethod.POST)
	public String update(
	@RequestParam(value="edit",defaultValue="0") Integer edit,
	@ModelAttribute Event item,
	@RequestParam(value="file") MultipartFile file,
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
		Event event = eventService.findById(id);
		try {
			if(file.getSize() > 0){
				String path = FileUtils.saveFileOrigin(file,"upload", servletContext);
				event.setImageUrl(path);
				event.setImageName(file.getOriginalFilename());
			}
			event.setTitle( item.getTitle() );
			event.setContent( item.getContent() );
			event.setUpdateDate( DataUtils.getNowDate() );
			event = eventService.update(event);
			model.addAttribute("item", event);
		} catch(Exception e) {
			System.out.println(e);
		}
		return "redirect:/"+JSP_EDIT+"/"+id;
	}
	
	

	@RequestMapping(value = "/delete/{id}")
	public String delete(
	Model model, 
	HttpSession session,
	@PathVariable("id") Integer id ) {
	eventService.delete(id);
	return "redirect:/"+JSP_LIST;
	}

}
