/*
 * Created on 23 thg 9 2016 ( Time 15:40:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.web.controller;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import org.springframework.web.bind.annotation.ModelAttribute;


//--- Common classes
import org.trams.web.common.AbstractController;
import org.trams.web.common.Pager;
import org.trams.web.common.utils.DataUtils;
import org.trams.web.common.Login;
import org.trams.bean.jpa.FaqEntity;

//--- Entities
import org.trams.bean.Faq;

//--- Services 
import org.trams.business.service.FaqService;

/**
 * Spring MVC controller for 'Faq' management.
 */
@Controller
@RequestMapping("/faq")
public class FaqController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "faq";

	private static final Integer PAGE_SIZE   = 10;

	private static String nav = "faq";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_CREATE   = "faq/create";
	private static final String JSP_LIST   = "faq/list";
	private static final String JSP_EDIT   = "faq/edit";
	private static final String JSP_DETAIL   = "faq/detail";
	private static final String JSP_LOGIN   = "redirect:/login";
	private static final String MAIN_LIST_NAME   = "list";
	//--- Main entity service
	@Resource
    private FaqService faqService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public FaqController() {
		super(FaqController.class, MAIN_ENTITY_NAME );
		log("FaqController created.");
	}

	@RequestMapping("/list")
	public String list(
			@RequestParam(value="page",defaultValue="1") Integer page,
			@RequestParam(value="type",defaultValue="") String type,
			@RequestParam(value="key",defaultValue="") String key,
			@RequestParam(value="delete",defaultValue="0") Integer delete,
			HttpSession session,
			Model model) {
		if(key==null){
			key="";
		}
		if(type==null){
			type="";
		}
		if(delete>0){
			try {
				faqService.delete(delete);
			} catch (Exception e) {
				// TODO: handle exception
			}
		}
		Page<FaqEntity> listPage = null;
		if(type == ""){
			listPage = faqService.listPaging(page, PAGE_SIZE);
		}else if(type.equals("title")){
			listPage = faqService.listPagingByQuestion("%"+key+"%", page, PAGE_SIZE);
		}else if(type.equals("category")){
			listPage = faqService.listPagingByCategoryName("%"+key+"%", page, PAGE_SIZE);
		}
		model.addAttribute(MAIN_LIST_NAME, listPage);	
		model.addAttribute("key", key);
		model.addAttribute("type", type);
		model.addAttribute("activePage", nav);
		model.addAttribute("pagination_navigator", "/faq/list");
		new Pager<FaqEntity>(listPage).setSetting(model, "type="+type+"&amp;key="+key+"&amp;");		
		return JSP_LIST;
	}

	
	@RequestMapping("/detail/{id}")
	public String detail(
	Model model, 
	HttpSession session,
	@PathVariable("id") Integer id) {
		Faq faq = faqService.findById(id);
		model.addAttribute("faq", faq);
		model.addAttribute("activePage", nav);
		return JSP_DETAIL;
	}
	@RequestMapping(value = "/create", method = RequestMethod.GET ) 
	public String create(
			HttpSession session,
			Model model) {
		log("Action 'create'");
		model.addAttribute("activePage", nav);
		return JSP_CREATE;
	}

	@RequestMapping(value = "/create", method = RequestMethod.POST ) 
	public String create(
			HttpSession session,
			@ModelAttribute Faq faq,
			Model model) {
		log("Action 'create'");
		try {
			if(faq.getCategoryId() == 1){
				faq.setCategoryName("청강/수강신청");
			}else if(faq.getCategoryId() == 2){
				faq.setCategoryName("취소/환불");
			}else if(faq.getCategoryId() == 3){
				faq.setCategoryName("기타");
			}
			faq.setCreateDate( DataUtils.getNowDate() );
			faq.setUpdateDate( DataUtils.getNowDate() );
			faqService.create(faq);
			return "redirect:/"+JSP_LIST;
		} catch(Exception e) {
			System.out.println(e);
			return JSP_CREATE;
		}
	}

	@RequestMapping(value = "/edit/{id}", method = RequestMethod.GET)
	public String update(
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
		Faq faq = faqService.findById(id);
		try {
			model.addAttribute("item", faq);
			model.addAttribute("activePage", nav);
			return JSP_EDIT;
		} catch(Exception e) {
			return JSP_LIST;
		}
	}
	
	@RequestMapping(value = "/edit/{id}", method = RequestMethod.POST)
	public String update(
	@RequestParam(value="edit",defaultValue="0") Integer edit,
	@ModelAttribute Faq item,
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
		Faq faq = faqService.findById(id);
		try {
			faq.setCategoryId( item.getCategoryId() );
			if(item.getCategoryId() == 1){
				faq.setCategoryName("청강/수강신청");
			}else if(item.getCategoryId() == 2){
				faq.setCategoryName("취소/환불");
			}else if(item.getCategoryId() == 3){
				faq.setCategoryName("기타");
			}
			faq.setQuestion( item.getQuestion() );
			faq.setAnswer( item.getAnswer() );
			faq.setUpdateDate( DataUtils.getNowDate() );
			faq = faqService.update(faq);
			model.addAttribute("item", faq);
		} catch(Exception e) {
			System.out.println(e);
		}
		return "redirect:/"+JSP_LIST;
	}
	
	

	@RequestMapping(value = "/delete/{id}")
	public String delete(
	Model model, 
	HttpSession session,
	@PathVariable("id") Integer id ) {
	faqService.delete(id);
	return "redirect:/"+JSP_LIST;
	}

}
