/*
 * Created on 22 thg 8 2016 ( Time 15:01:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.web.controller;


import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.trams.web.common.AbstractController;
import org.trams.web.common.ApplicationDefine;
import org.trams.web.common.Pager;
import org.trams.web.common.Login;
import org.trams.web.common.utils.ConstantUtils;
import org.trams.web.common.utils.DataUtils;
import org.trams.bean.Program;
import org.trams.bean.User;
import org.trams.bean.UserItem;
//--- Entities
import org.trams.business.service.ProgramService;
//--- Services 
import org.trams.business.service.UserService;

@Controller
@RequestMapping("")
public class MainController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "main";
	private static final String MAIN_LIST_NAME = "list";

	private static final String TOTAL_PAGE   = "pages";

	private static final String CURRENT_PAGE   = "pageNumber";

	private static final String LIST_PAGES   = "listPages";

	private static final Integer PAGE_SIZE   = 10;

	private static String nav = "main";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_INDEX   = "redirect:/user/list";
	private static final String JSP_LOGIN   = "redirect:/login";
	private static final String JSP_MAP   = "map";


	//Resource
	@Resource
	private UserService userService;
	
	@Resource
	private ProgramService programService;
	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public MainController() {
		super(MainController.class, MAIN_ENTITY_NAME);
		log("UserController created.");
	}
	
	@RequestMapping(value="/login",method=RequestMethod.POST)
	public String login(
			@RequestParam(value="username",defaultValue="") String username,
			@RequestParam(value="password",defaultValue="") String password,
			@RequestParam(value = "remember", defaultValue = "") String remember,
			Model model, HttpSession session, HttpServletResponse response) {
		if(username == null || password == null){
			model.addAttribute("username", username);
			model.addAttribute("login_success", 0);
			return "login";
		}
		User user = userService.loginAdminPage(username, DataUtils.getMD5(password));
		if(user!=null){
			UserItem u = new UserItem();
			u.setType(user.getType());
			u.setRole(user.getRole());
			u.setId(user.getId());
			Login.saveUser(u, session);
			if (remember != null && remember.equalsIgnoreCase("on")) {
				Cookie name = new Cookie("username", username);
				Cookie pass = new Cookie("password", password);
				// Set expiry date after 24 Hrs for both the cookies.
				name.setMaxAge(60 * 60 * 24);
				pass.setMaxAge(60 * 60 * 24);
				// Add both the cookies in the response header.
				response.addCookie(name);
				response.addCookie(pass);
				model.addAttribute("user", user);
				model.addAttribute("login_success", 1);
			}
			if(user.getRole() == ApplicationDefine.USER_PROCEDURE ){
				return "redirect:/program";
			}else{
				return JSP_INDEX;
			}
			
		}else{
			model.addAttribute("username", username);
			model.addAttribute("login_success", 0);
			return "login";
		}
		
	}
	

	@RequestMapping(value = "/map/{id}", method = RequestMethod.GET ) 
	public String map(
			@PathVariable("id") Integer id,
			HttpSession session,
			Model model) {
		log("Action 'create'");
		Program p = programService.findById(id);
		model.addAttribute("latitude", p.getLatitude());
		model.addAttribute("longtitude", p.getLongitude());
		return JSP_MAP;
	}
	
	@RequestMapping(value="/login",method=RequestMethod.GET)
	public String login(Model model, HttpSession session) {
			return "login";	
		}
	
	@RequestMapping("/logout")
	public String logout(Model model, HttpSession session) {
			Login.removeUserLogin(session);
			return "redirect:/login";	
		}
	
	
	@RequestMapping(value={"/index"})
	public String index(
			Model model,HttpSession session) {
			return "redirect:/user/list";
	}
	
	@RequestMapping(value="",method=RequestMethod.GET)
	public String login2(Model model, HttpSession session) {
			return JSP_LOGIN;	
		}

}
