/*
 * Created on 11 thg 10 2016 ( Time 15:37:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.trams.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "purchase"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="purchase", catalog="whelearn" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PurchaseEntity.countAll", query="SELECT COUNT(x) FROM PurchaseEntity x" )
} )
public class PurchaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="fullname", length=200)
    private String     fullname     ;

    @Column(name="phone", length=15)
    private String     phone        ;

    @Column(name="coupon_id")
    private Integer    couponId     ;

    @Column(name="total_money", nullable=false)
    private Integer    totalMoney   ;

    @Column(name="payment_method_name", length=500)
    private String     paymentMethodName ;

    @Column(name="refund_money")
    private Integer    refundMoney  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="refund_date")
    private Date       refundDate   ;

    @Column(name="tid", length=200)
    private String     tid          ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date")
    private Date       createDate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date")
    private Date       updateDate   ;

    @Column(name="order_program")
    private Integer    orderProgram ;

    @Column(name="account_info", length=500)
    private String accountInfo;
    
	// "userId" (column "user_id") is not defined by itself because used as FK in a link 
	// "programId" (column "program_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	
    @ManyToOne
    @JoinColumn(name="program_id", referencedColumnName="id")
    private ProgramEntity program     ;

	
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id")
    private UserEntity user        ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PurchaseEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : fullname ( VARCHAR ) 
    public void setFullname( String fullname ) {
        this.fullname = fullname;
    }
    public String getFullname() {
        return this.fullname;
    }

    //--- DATABASE MAPPING : phone ( VARCHAR ) 
    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    //--- DATABASE MAPPING : coupon_id ( INT ) 
    public void setCouponId( Integer couponId ) {
        this.couponId = couponId;
    }
    public Integer getCouponId() {
        return this.couponId;
    }

    //--- DATABASE MAPPING : total_money ( INT ) 
    public void setTotalMoney( Integer totalMoney ) {
        this.totalMoney = totalMoney;
    }
    public Integer getTotalMoney() {
        return this.totalMoney;
    }

    //--- DATABASE MAPPING : payment_method_name ( VARCHAR ) 
    public void setPaymentMethodName( String paymentMethodName ) {
        this.paymentMethodName = paymentMethodName;
    }
    public String getPaymentMethodName() {
        return this.paymentMethodName;
    }

    //--- DATABASE MAPPING : refund_money ( INT ) 
    public void setRefundMoney( Integer refundMoney ) {
        this.refundMoney = refundMoney;
    }
    public Integer getRefundMoney() {
        return this.refundMoney;
    }

    //--- DATABASE MAPPING : refund_date ( DATETIME ) 
    public void setRefundDate( Date refundDate ) {
        this.refundDate = refundDate;
    }
    public Date getRefundDate() {
        return this.refundDate;
    }

    //--- DATABASE MAPPING : tid ( VARCHAR ) 
    public void setTid( String tid ) {
        this.tid = tid;
    }
    public String getTid() {
        return this.tid;
    }

    //--- DATABASE MAPPING : create_date ( DATETIME ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : update_date ( DATETIME ) 
    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    //--- DATABASE MAPPING : order_program ( INT ) 
    public void setOrderProgram( Integer orderProgram ) {
        this.orderProgram = orderProgram;
    }
    public Integer getOrderProgram() {
        return this.orderProgram;
    }

    public String getAccountInfo() {
		return accountInfo;
	}

	public void setAccountInfo(String accountInfo) {
		this.accountInfo = accountInfo;
	}
	
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setProgram( ProgramEntity program ) {
        this.program = program;
    }
    public ProgramEntity getProgram() {
        return this.program;
    }

    public void setUser( UserEntity user ) {
        this.user = user;
    }
    public UserEntity getUser() {
        return this.user;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(fullname);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(couponId);
        sb.append("|");
        sb.append(totalMoney);
        sb.append("|");
        sb.append(paymentMethodName);
        sb.append("|");
        sb.append(refundMoney);
        sb.append("|");
        sb.append(refundDate);
        sb.append("|");
        sb.append(tid);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(orderProgram);
        return sb.toString(); 
    } 

}
