/*
 * Created on 6 thg 10 2016 ( Time 17:03:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.trams.bean.jpa;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnore;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "time_learn"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="time_learn", catalog="whelearn" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TimeLearnEntity.countAll", query="SELECT COUNT(x) FROM TimeLearnEntity x" )
} )
public class TimeLearnEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="date_learn")
    private Date       dateLearn    ;

    @Temporal(TemporalType.TIME)
    @Column(name="from_time")
    private Date       fromTime     ;

    @Temporal(TemporalType.TIME)
    @Column(name="to_time")
    private Date       toTime       ;

    @Column(name="opening_day")
    private Integer    openingDay   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date")
    private Date       createDate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date")
    private Date       updateDate   ;

	// "programId" (column "program_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	
    @ManyToOne
    @JoinColumn(name="program_id", referencedColumnName="id")
    private ProgramEntity program     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TimeLearnEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : date_learn ( DATE ) 
    public void setDateLearn( Date dateLearn ) {
        this.dateLearn = dateLearn;
    }
    public Date getDateLearn() {
        return this.dateLearn;
    }

    //--- DATABASE MAPPING : from_time ( TIME ) 
    public void setFromTime( Date fromTime ) {
        this.fromTime = fromTime;
    }
    public Date getFromTime() {
        return this.fromTime;
    }

    //--- DATABASE MAPPING : to_time ( TIME ) 
    public void setToTime( Date toTime ) {
        this.toTime = toTime;
    }
    public Date getToTime() {
        return this.toTime;
    }

    //--- DATABASE MAPPING : opening_day ( INT ) 
    public void setOpeningDay( Integer openingDay ) {
        this.openingDay = openingDay;
    }
    public Integer getOpeningDay() {
        return this.openingDay;
    }

    //--- DATABASE MAPPING : create_date ( DATETIME ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : update_date ( DATETIME ) 
    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setProgram( ProgramEntity program ) {
        this.program = program;
    }
    public ProgramEntity getProgram() {
        return this.program;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(dateLearn);
        sb.append("|");
        sb.append(fromTime);
        sb.append("|");
        sb.append(toTime);
        sb.append("|");
        sb.append(openingDay);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 

}
