/*
 * Created on 1 thg 9 2016 ( Time 10:04:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class QuestionAnswer implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer programId;


    private Integer askUserId;


    private Integer answerUserId;

    @Size( max = 500 )
    private String questioin;

    @Size( max = 500 )
    private String answer;


    private Date askDate;


    private Date answerDate;


    private Date createDate;


    private Date updateDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setProgramId( Integer programId ) {
        this.programId = programId;
    }
    public Integer getProgramId() {
        return this.programId;
    }

    public void setAskUserId( Integer askUserId ) {
        this.askUserId = askUserId;
    }
    public Integer getAskUserId() {
        return this.askUserId;
    }

    public void setAnswerUserId( Integer answerUserId ) {
        this.answerUserId = answerUserId;
    }
    public Integer getAnswerUserId() {
        return this.answerUserId;
    }

    public void setQuestioin( String questioin ) {
        this.questioin = questioin;
    }
    public String getQuestioin() {
        return this.questioin;
    }

    public void setAnswer( String answer ) {
        this.answer = answer;
    }
    public String getAnswer() {
        return this.answer;
    }

    public void setAskDate( Date askDate ) {
        this.askDate = askDate;
    }
    public Date getAskDate() {
        return this.askDate;
    }

    public void setAnswerDate( Date answerDate ) {
        this.answerDate = answerDate;
    }
    public Date getAnswerDate() {
        return this.answerDate;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(programId);
        sb.append("|");
        sb.append(askUserId);
        sb.append("|");
        sb.append(answerUserId);
        sb.append("|");
        sb.append(questioin);
        sb.append("|");
        sb.append(answer);
        sb.append("|");
        sb.append(askDate);
        sb.append("|");
        sb.append(answerDate);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
