/*
 * Created on 27 thg 9 2016 ( Time 11:02:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Setting implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer uploadContentNotification;

    @NotNull
    private Integer openCourseNotification;

    @NotNull
    private Integer commentNotification;

    @NotNull
    private Integer couponNotification;

    @NotNull
    private Integer noticeNotification;

    @NotNull
    private Integer finishRegisterCourseNotification;

    @NotNull
    private Integer finishPayCourseNotification;

    @NotNull
    private Integer postQuestionCourseNotification;

    @NotNull
    private Integer postCommentCourseNotification;


    private Date createDate;


    private Date updateDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUploadContentNotification( Integer uploadContentNotification ) {
        this.uploadContentNotification = uploadContentNotification;
    }
    public Integer getUploadContentNotification() {
        return this.uploadContentNotification;
    }

    public void setOpenCourseNotification( Integer openCourseNotification ) {
        this.openCourseNotification = openCourseNotification;
    }
    public Integer getOpenCourseNotification() {
        return this.openCourseNotification;
    }

    public void setCommentNotification( Integer commentNotification ) {
        this.commentNotification = commentNotification;
    }
    public Integer getCommentNotification() {
        return this.commentNotification;
    }

    public void setCouponNotification( Integer couponNotification ) {
        this.couponNotification = couponNotification;
    }
    public Integer getCouponNotification() {
        return this.couponNotification;
    }

    public void setNoticeNotification( Integer noticeNotification ) {
        this.noticeNotification = noticeNotification;
    }
    public Integer getNoticeNotification() {
        return this.noticeNotification;
    }

    public void setFinishRegisterCourseNotification( Integer finishRegisterCourseNotification ) {
        this.finishRegisterCourseNotification = finishRegisterCourseNotification;
    }
    public Integer getFinishRegisterCourseNotification() {
        return this.finishRegisterCourseNotification;
    }

    public void setFinishPayCourseNotification( Integer finishPayCourseNotification ) {
        this.finishPayCourseNotification = finishPayCourseNotification;
    }
    public Integer getFinishPayCourseNotification() {
        return this.finishPayCourseNotification;
    }

    public void setPostQuestionCourseNotification( Integer postQuestionCourseNotification ) {
        this.postQuestionCourseNotification = postQuestionCourseNotification;
    }
    public Integer getPostQuestionCourseNotification() {
        return this.postQuestionCourseNotification;
    }

    public void setPostCommentCourseNotification( Integer postCommentCourseNotification ) {
        this.postCommentCourseNotification = postCommentCourseNotification;
    }
    public Integer getPostCommentCourseNotification() {
        return this.postCommentCourseNotification;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(uploadContentNotification);
        sb.append("|");
        sb.append(openCourseNotification);
        sb.append("|");
        sb.append(commentNotification);
        sb.append("|");
        sb.append(couponNotification);
        sb.append("|");
        sb.append(noticeNotification);
        sb.append("|");
        sb.append(finishRegisterCourseNotification);
        sb.append("|");
        sb.append(finishPayCourseNotification);
        sb.append("|");
        sb.append(postQuestionCourseNotification);
        sb.append("|");
        sb.append(postCommentCourseNotification);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
