/*
 * Created on 6 thg 10 2016 ( Time 17:03:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class TimeLearn implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer programId;


    private Date dateLearn;


    private Date fromTime;


    private Date toTime;


    private Integer openingDay;


    private Date createDate;


    private Date updateDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setProgramId( Integer programId ) {
        this.programId = programId;
    }
    public Integer getProgramId() {
        return this.programId;
    }

    public void setDateLearn( Date dateLearn ) {
        this.dateLearn = dateLearn;
    }
    public Date getDateLearn() {
        return this.dateLearn;
    }

    public void setFromTime( Date fromTime ) {
        this.fromTime = fromTime;
    }
    public Date getFromTime() {
        return this.fromTime;
    }

    public void setToTime( Date toTime ) {
        this.toTime = toTime;
    }
    public Date getToTime() {
        return this.toTime;
    }

    public void setOpeningDay( Integer openingDay ) {
        this.openingDay = openingDay;
    }
    public Integer getOpeningDay() {
        return this.openingDay;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(programId);
        sb.append("|");
        sb.append(dateLearn);
        sb.append("|");
        sb.append(fromTime);
        sb.append("|");
        sb.append(toTime);
        sb.append("|");
        sb.append(openingDay);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
