/*
 * Created on 31 thg 10 2016 ( Time 13:26:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 100 )
    private String password;

    @NotNull
    @Size( min = 1, max = 200 )
    private String nickname;

    @Size( max = 255 )
    private String fullname;


    private Short gender;


    private Date dayOfBirth;

    @Size( max = 200 )
    private String phone;

    @Size( max = 255 )
    private String email;

    @Size( max = 500 )
    private String address;


    private Integer role;


    private Integer active;


    private Integer type;

    @Size( max = 300 )
    private String token;

    @Size( max = 500 )
    private String fcmToken;


    private Integer pushFcmToken;


    private Integer isDelete;


    private Date createDate;


    private Date updateDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }

    public void setNickname( String nickname ) {
        this.nickname = nickname;
    }
    public String getNickname() {
        return this.nickname;
    }

    public void setFullname( String fullname ) {
        this.fullname = fullname;
    }
    public String getFullname() {
        return this.fullname;
    }

    public void setGender( Short gender ) {
        this.gender = gender;
    }
    public Short getGender() {
        return this.gender;
    }

    public void setDayOfBirth( Date dayOfBirth ) {
        this.dayOfBirth = dayOfBirth;
    }
    public Date getDayOfBirth() {
        return this.dayOfBirth;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    public void setRole( Integer role ) {
        this.role = role;
    }
    public Integer getRole() {
        return this.role;
    }

    public void setActive( Integer active ) {
        this.active = active;
    }
    public Integer getActive() {
        return this.active;
    }

    public void setType( Integer type ) {
        this.type = type;
    }
    public Integer getType() {
        return this.type;
    }

    public void setToken( String token ) {
        this.token = token;
    }
    public String getToken() {
        return this.token;
    }

    public void setFcmToken( String fcmToken ) {
        this.fcmToken = fcmToken;
    }
    public String getFcmToken() {
        return this.fcmToken;
    }

    public void setPushFcmToken( Integer pushFcmToken ) {
        this.pushFcmToken = pushFcmToken;
    }
    public Integer getPushFcmToken() {
        return this.pushFcmToken;
    }

    public void setIsDelete( Integer isDelete ) {
        this.isDelete = isDelete;
    }
    public Integer getIsDelete() {
        return this.isDelete;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(nickname);
        sb.append("|");
        sb.append(fullname);
        sb.append("|");
        sb.append(gender);
        sb.append("|");
        sb.append(dayOfBirth);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(role);
        sb.append("|");
        sb.append(active);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(token);
        sb.append("|");
        sb.append(fcmToken);
        sb.append("|");
        sb.append(pushFcmToken);
        sb.append("|");
        sb.append(isDelete);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
