/*
 * Created on 24 thg 8 2016 ( Time 15:11:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class UserFeed implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer providerId;
    
    private Integer userRegisterId;
    
    private String nickname;
    
    private String phone;
    
    private Integer programId;
    
    private String title;
    
    private Date timeLearn;

	public Integer getProviderId() {
		return providerId;
	}

	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	public Integer getUserRegisterId() {
		return userRegisterId;
	}

	public void setUserRegisterId(Integer userRegisterId) {
		this.userRegisterId = userRegisterId;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getProgramId() {
		return programId;
	}

	public void setProgramId(Integer programId) {
		this.programId = programId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getTimeLearn() {
		return timeLearn;
	}

	public void setTimeLearn(Date timeLearn) {
		this.timeLearn = timeLearn;
	}
    
    
}
