/*
 * Created on 3 11�� 2016 ( Time 16:33:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service;

import java.util.List;
import org.trams.bean.jpa.BankInfoEntity;
import org.trams.bean.BankInfo;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity BankInfo.
 */
public interface BankInfoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	BankInfo findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<BankInfo> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<BankInfoEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	BankInfo save(BankInfo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	BankInfo update(BankInfo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	BankInfo create(BankInfo entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<BankInfoEntity> listPaging(Integer page,Integer size);
	

	BankInfo findByBankCode( String bankCode  ) ;
}
