/*
 * Created on 23 thg 8 2016 ( Time 16:20:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service;

import java.util.List;
import org.trams.bean.jpa.CategoryEntity;
import org.trams.bean.Category;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity Category.
 */
public interface CategoryService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Category findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Category> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<CategoryEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Category save(Category entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Category update(Category entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Category create(Category entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<CategoryEntity> listPaging(Integer page,Integer size);
	
	void updateCategoryCount(Integer category_id);

	List<CategoryEntity> findAllOrder(Integer page,Integer size, String oderBy);
}
