/*
 * Created on 8 thg 9 2016 ( Time 13:14:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service;

import java.util.List;
import org.trams.bean.jpa.KeywordProgramEntity;
import org.trams.bean.KeywordProgram;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity KeywordProgram.
 */
public interface KeywordProgramService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param programId
	 * @return entity
	 */
	KeywordProgram findById( Integer programId  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<KeywordProgram> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<KeywordProgramEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	KeywordProgram save(KeywordProgram entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	KeywordProgram update(KeywordProgram entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	KeywordProgram create(KeywordProgram entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param programId
	 */
	void delete( Integer programId );

	Page<KeywordProgramEntity> listPaging(Integer page,Integer size);
	
	KeywordProgram findByProgramId(Integer programId);

}
