/*
 * Created on 23 thg 8 2016 ( Time 16:20:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service;

import java.util.List;
import org.trams.bean.jpa.LikesEntity;
import org.trams.bean.Likes;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Likes.
 */
public interface LikesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Likes findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Likes> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<LikesEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Likes save(Likes entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Likes update(Likes entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Likes create(Likes entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<LikesEntity> listPaging(Integer page,Integer size);
	
	Page<LikesEntity> listPagingByUserId( Integer page, Integer size, Integer userId);

	LikesEntity findByUserIdAndThreadIdAndType( Integer userId, Integer contentId, Integer type);

	void deleteLike(Integer userId, Integer threadId, Integer type);

}
