/*
 * Created on 23 thg 8 2016 ( Time 16:20:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service;

import java.util.List;
import org.trams.bean.jpa.NoticeEntity;
import org.trams.bean.Notice;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Notice.
 */
public interface NoticeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Notice findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Notice> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<NoticeEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Notice save(Notice entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Notice update(Notice entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Notice create(Notice entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<NoticeEntity> listPaging(Integer page,Integer size);
	
	Page<NoticeEntity> findByTitle(String title, Integer page, Integer size);



}
