/*
 * Created on 23 thg 8 2016 ( Time 16:20:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service;

import java.util.List;
import org.trams.bean.jpa.ProgramViewEntity;
import org.trams.bean.ProgramView;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity ProgramView.
 */
public interface ProgramViewService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ProgramView findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<ProgramView> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<ProgramViewEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ProgramView save(ProgramView entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ProgramView update(ProgramView entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ProgramView create(ProgramView entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<ProgramViewEntity> listPaging(Integer page,Integer size);
	
	Page<ProgramViewEntity> listPagingByUserId( Integer page, Integer size, Integer userId);

	Page<ProgramViewEntity> listPagingByUsernameAndTitle( String nickname, String title , Integer page, Integer size);

	List<ProgramViewEntity> listPagingByUserIdAndProgramId( Integer userId, Integer programId);
}
