/*
 * Created on 30 thg 8 2016 ( Time 15:36:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service;

import java.util.Date;
import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.bean.ProgramRegister;
import org.trams.bean.UserFeed;
import org.trams.bean.jpa.ProgramRegisterEntity;
import org.trams.bean.jpa.ProgramRegisterEntityCustom;

/**
 * Business Service Interface for entity ProgramRegister.
 */
public interface ProgramRegisterService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ProgramRegister findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<ProgramRegister> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<ProgramRegisterEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ProgramRegister save(ProgramRegister entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ProgramRegister update(ProgramRegister entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ProgramRegister create(ProgramRegister entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<ProgramRegisterEntity> listPaging(Integer page,Integer size);
	
	Page<ProgramRegisterEntity> listPagingByUserId( Integer page, Integer size, Integer userId);

	List<UserFeed> listPagingFeedUser( Date date, Integer page, Integer size);
	
	Integer totalFeedUser( Date date);
	
	List<UserFeed> listPagingFeedUserByNickname( Date date, String name, Integer page, Integer size);
	
	Integer totalFeedUserByNickname( Date date, String nickname);
	
	List<UserFeed> listPagingFeedUserByTitle( Date date, String name, Integer page, Integer size);
	
	Integer totalFeedUserByTitle( Date date, String title);
	
	List<ProgramRegisterEntity> listByUserIdAndProgramId( Integer userId, Integer programId);
	
	Page<ProgramRegisterEntityCustom> listPagingByUserIdCustom( Integer userId, Integer page, Integer size);
	
	
}
