/*
 * Created on 26 thg 8 2016 ( Time 11:30:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service;

import java.util.Date;
import java.util.List;

import org.trams.bean.jpa.CommentNotification;
import org.trams.bean.jpa.SettingEntity;
import org.trams.bean.Setting;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Setting.
 */
public interface SettingService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Setting findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Setting> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<SettingEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Setting save(Setting entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Setting update(Setting entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Setting create(Setting entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<SettingEntity> listPaging(Integer page,Integer size);
	
	Page<SettingEntity> listPagingByUserId( Integer page, Integer size, Integer userId);

	SettingEntity findByUserId( Integer userId);

	List<String> getFCMTokenBy_UploadContentNotification();
	
	List<String> getFCMTokenBy_OpenCourseNotification();
	
	List<CommentNotification> getFCMTokenBy_CommentNotification(String now);
	
	List<String> getFCMTokenBy_NoticeNotification();
		
	List<String> getFCMTokenBy_FinishPayCourseNotification();
	
	List<String> getFCMTokenBy_PostQuestionCourseNotification();
	
	List<String> getFCMTokenBy_PostCommentCourseNotification();
	
	List<String> getFCMTokenBy_CouponNotification_Join(Integer countDate);
	
	List<String> getFCMTokenBy_CouponNotification_Use_Comment(Integer countDate, Integer couponId);
	
	List<CommentNotification> getFCMTokenBy_FinishRegisterCourseNotification(Date deadLine, Integer hour );
}
