/*
 * Created on 29 thg 8 2016 ( Time 13:08:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service;

import java.sql.Time;
import java.util.Date;
import java.util.List;
import org.trams.bean.jpa.TimeLearnEntity;
import org.trams.bean.TimeLearn;
import org.joda.time.DateTime;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity TimeLearn.
 */
public interface TimeLearnService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	TimeLearn findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<TimeLearn> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<TimeLearnEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TimeLearn save(TimeLearn entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TimeLearn update(TimeLearn entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TimeLearn create(TimeLearn entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<TimeLearnEntity> listPaging(Integer page,Integer size);
	
	List<TimeLearnEntity> findByMontYear( Integer month, Integer year);

	List<TimeLearnEntity> findByProgramId( Integer program_id);
	
	void deleteByProgramId( Integer program_id);
	
	void createTimeLearn(Integer programId, Date date_learn, Date from, Date to, Integer opening_day, Date create_date, Date update_date);
	
	List<TimeLearnEntity> findByMontYearAndUserId( Integer month, Integer year, Integer user_id);
	
	List<String> findTitleFinishProgram( Date date, Integer hour);
}
