/*
 * Created on 3 11 2016 ( Time 16:33:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.bean.BankInfo;
import org.trams.bean.jpa.BankInfoEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BankInfoServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BankInfoServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'BankInfoEntity' to 'BankInfo'
	 * @param bankInfoEntity
	 */
	public BankInfo mapBankInfoEntityToBankInfo(BankInfoEntity bankInfoEntity) {
		if(bankInfoEntity == null) {
			return null;
		}

		//--- Generic mapping 
		BankInfo bankInfo = map(bankInfoEntity, BankInfo.class);

		return bankInfo;
	}
	
	/**
	 * Mapping from 'BankInfo' to 'BankInfoEntity'
	 * @param bankInfo
	 * @param bankInfoEntity
	 */
	public void mapBankInfoToBankInfoEntity(BankInfo bankInfo, BankInfoEntity bankInfoEntity) {
		if(bankInfo == null) {
			return;
		}

		//--- Generic mapping 
		map(bankInfo, bankInfoEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}