/*
 * Created on 19 thg 12 2016 ( Time 16:23:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.bean.Content;
import org.trams.bean.jpa.ContentEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ContentServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ContentServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ContentEntity' to 'Content'
	 * @param contentEntity
	 */
	public Content mapContentEntityToContent(ContentEntity contentEntity) {
		if(contentEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Content content = map(contentEntity, Content.class);

		return content;
	}
	
	/**
	 * Mapping from 'Content' to 'ContentEntity'
	 * @param content
	 * @param contentEntity
	 */
	public void mapContentToContentEntity(Content content, ContentEntity contentEntity) {
		if(content == null) {
			return;
		}

		//--- Generic mapping 
		map(content, contentEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}