/*
 * Created on 19 thg 12 2016 ( Time 16:41:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.bean.ContentsRecom;
import org.trams.bean.jpa.ContentsRecomEntity;
import org.trams.bean.jpa.ContentEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ContentsRecomServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ContentsRecomServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ContentsRecomEntity' to 'ContentsRecom'
	 * @param contentsRecomEntity
	 */
	public ContentsRecom mapContentsRecomEntityToContentsRecom(ContentsRecomEntity contentsRecomEntity) {
		if(contentsRecomEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ContentsRecom contentsRecom = map(contentsRecomEntity, ContentsRecom.class);

		//--- Link mapping ( link to Content )
		if(contentsRecomEntity.getContent() != null) {
			contentsRecom.setContentId(contentsRecomEntity.getContent().getId());
		}
		return contentsRecom;
	}
	
	/**
	 * Mapping from 'ContentsRecom' to 'ContentsRecomEntity'
	 * @param contentsRecom
	 * @param contentsRecomEntity
	 */
	public void mapContentsRecomToContentsRecomEntity(ContentsRecom contentsRecom, ContentsRecomEntity contentsRecomEntity) {
		if(contentsRecom == null) {
			return;
		}

		//--- Generic mapping 
		map(contentsRecom, contentsRecomEntity);

		//--- Link mapping ( link : contentsRecom )
		if( hasLinkToContent(contentsRecom) ) {
			ContentEntity content1 = new ContentEntity();
			content1.setId( contentsRecom.getContentId() );
			contentsRecomEntity.setContent( content1 );
		} else {
			contentsRecomEntity.setContent( null );
		}
		
		
		

	}
	
	/**
	 * Verify that Content id is valid.
	 * @param Content Content
	 * @return boolean
	 */
	private boolean hasLinkToContent(ContentsRecom contentsRecom) {
		if(contentsRecom.getContentId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}