/*
 * Created on 23 thg 8 2016 ( Time 16:20:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.bean.Faq;
import org.trams.bean.jpa.FaqEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class FaqServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public FaqServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'FaqEntity' to 'Faq'
	 * @param faqEntity
	 */
	public Faq mapFaqEntityToFaq(FaqEntity faqEntity) {
		if(faqEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Faq faq = map(faqEntity, Faq.class);

		return faq;
	}
	
	/**
	 * Mapping from 'Faq' to 'FaqEntity'
	 * @param faq
	 * @param faqEntity
	 */
	public void mapFaqToFaqEntity(Faq faq, FaqEntity faqEntity) {
		if(faq == null) {
			return;
		}

		//--- Generic mapping 
		map(faq, faqEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}