/*
 * Created on 28 thg 9 2016 ( Time 16:10:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.bean.Keyword;
import org.trams.bean.jpa.KeywordEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class KeywordServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public KeywordServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'KeywordEntity' to 'Keyword'
	 * @param keywordEntity
	 */
	public Keyword mapKeywordEntityToKeyword(KeywordEntity keywordEntity) {
		if(keywordEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Keyword keyword = map(keywordEntity, Keyword.class);

		return keyword;
	}
	
	/**
	 * Mapping from 'Keyword' to 'KeywordEntity'
	 * @param keyword
	 * @param keywordEntity
	 */
	public void mapKeywordToKeywordEntity(Keyword keyword, KeywordEntity keywordEntity) {
		if(keyword == null) {
			return;
		}

		//--- Generic mapping 
		map(keyword, keywordEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}