/*
 * Created on 22 thg 11 2016 ( Time 13:10:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.bean.KeywordProgram;
import org.trams.bean.jpa.KeywordProgramEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class KeywordProgramServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public KeywordProgramServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'KeywordProgramEntity' to 'KeywordProgram'
	 * @param keywordProgramEntity
	 */
	public KeywordProgram mapKeywordProgramEntityToKeywordProgram(KeywordProgramEntity keywordProgramEntity) {
		if(keywordProgramEntity == null) {
			return null;
		}

		//--- Generic mapping 
		KeywordProgram keywordProgram = map(keywordProgramEntity, KeywordProgram.class);

		return keywordProgram;
	}
	
	/**
	 * Mapping from 'KeywordProgram' to 'KeywordProgramEntity'
	 * @param keywordProgram
	 * @param keywordProgramEntity
	 */
	public void mapKeywordProgramToKeywordProgramEntity(KeywordProgram keywordProgram, KeywordProgramEntity keywordProgramEntity) {
		if(keywordProgram == null) {
			return;
		}

		//--- Generic mapping 
		map(keywordProgram, keywordProgramEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}