/*
 * Created on 5 thg 9 2016 ( Time 18:18:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.bean.ProgramView;
import org.trams.bean.jpa.ProgramViewEntity;
import org.trams.bean.jpa.ProgramEntity;
import org.trams.bean.jpa.UserEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ProgramViewServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ProgramViewServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ProgramViewEntity' to 'ProgramView'
	 * @param programViewEntity
	 */
	public ProgramView mapProgramViewEntityToProgramView(ProgramViewEntity programViewEntity) {
		if(programViewEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ProgramView programView = map(programViewEntity, ProgramView.class);

		//--- Link mapping ( link to Program )
		if(programViewEntity.getProgram() != null) {
			programView.setProgramId(programViewEntity.getProgram().getId());
		}
		//--- Link mapping ( link to User )
		if(programViewEntity.getUser() != null) {
			programView.setUserId(programViewEntity.getUser().getId());
		}
		return programView;
	}
	
	/**
	 * Mapping from 'ProgramView' to 'ProgramViewEntity'
	 * @param programView
	 * @param programViewEntity
	 */
	public void mapProgramViewToProgramViewEntity(ProgramView programView, ProgramViewEntity programViewEntity) {
		if(programView == null) {
			return;
		}

		//--- Generic mapping 
		map(programView, programViewEntity);

		//--- Link mapping ( link : programView )
		if( hasLinkToProgram(programView) ) {
			ProgramEntity program1 = new ProgramEntity();
			program1.setId( programView.getProgramId() );
			programViewEntity.setProgram( program1 );
		} else {
			programViewEntity.setProgram( null );
		}

		//--- Link mapping ( link : programView )
		if( hasLinkToUser(programView) ) {
			UserEntity user2 = new UserEntity();
			user2.setId( programView.getUserId() );
			programViewEntity.setUser( user2 );
		} else {
			programViewEntity.setUser( null );
		}

	}
	
	/**
	 * Verify that Program id is valid.
	 * @param Program Program
	 * @return boolean
	 */
	private boolean hasLinkToProgram(ProgramView programView) {
		if(programView.getProgramId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * Verify that User id is valid.
	 * @param User User
	 * @return boolean
	 */
	private boolean hasLinkToUser(ProgramView programView) {
		if(programView.getUserId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}