/*
 * Created on 24 thg 8 2016 ( Time 15:30:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.bean.QuestionAnswer;
import org.trams.bean.jpa.QuestionAnswerEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class QuestionAnswerServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public QuestionAnswerServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'QuestionAnswerEntity' to 'QuestionAnswer'
	 * @param questionAnswerEntity
	 */
	public QuestionAnswer mapQuestionAnswerEntityToQuestionAnswer(QuestionAnswerEntity questionAnswerEntity) {
		if(questionAnswerEntity == null) {
			return null;
		}

		//--- Generic mapping 
		QuestionAnswer questionAnswer = map(questionAnswerEntity, QuestionAnswer.class);

		return questionAnswer;
	}
	
	/**
	 * Mapping from 'QuestionAnswer' to 'QuestionAnswerEntity'
	 * @param questionAnswer
	 * @param questionAnswerEntity
	 */
	public void mapQuestionAnswerToQuestionAnswerEntity(QuestionAnswer questionAnswer, QuestionAnswerEntity questionAnswerEntity) {
		if(questionAnswer == null) {
			return;
		}

		//--- Generic mapping 
		map(questionAnswer, questionAnswerEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}